#!/bin/bash
# Run clang-format.

mongodir="$HOME/code/mongo"

if [ ! -e "$mongodir/buildscripts/clang_format.py" ]; then
    echo "Fatal: no clang_format in $mongodir/buildscripts"
    exit 1
fi

cd $mongodir
echo "python buildscripts/clang_format.py format"
python buildscripts/clang_format.py format
