# bash_aliases: user-defined aliases for bash

# Color support for ls and grep
if [ -x /usr/bin/dircolors ]; then
    if [ -r ~/.dircolors ]; then
        eval '$(dircolors -b ~/.dircolors)' || eval '$(dircolors -b)'
    fi

    alias ls='ls --color=auto --group-directories-first'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Listing directories
alias ll='ls -l'
alias la='ls -lA'
alias lh='ls -Aoh'
alias lt='ls -lAtr'
alias l.='ls -ld .*'
alias lll='ls -la | less'

# Moving around
alias ..='cd .. && ls -l'
alias home='cd && ls -l'

# Connecting to places
alias fly='ssh -X kds124@flyweight.cs.rutgers.edu'
alias eden='ssh kds124@eden.rutgers.edu'

# Start up programs with a GUI in the background
alias chrome='google-chrome > /dev/null 2>&1 &'
alias incognito='google-chrome --incognito > /dev/null 2>&1 &'

# Handy opener for files
if which xdg-open > /dev/null 2>&1 ; then
    alias open='xdg-open'
elif which gvfs-open > /dev/null 2>&1 ; then
    alias open='gvfs-open'
fi

# Set the desktop background
if which feh > /dev/null 2>&1 && test -d ~/Pictures ; then
    alias setbg='feh --bg-center --no-fehbg'
    alias randombg='setbg ~/Pictures/$(ls ~/Pictures | sort -R | tail -n1)'
fi
