# bash_aliases: user-defined aliases for bash

# Color support for ls and grep
if [ -x /usr/bin/dircolors ]; then
    eval $(dircolors -b)

    alias ls='ls --color=auto --group-directories-first'
    alias lll='ls -la --color=always | less -r'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Allows which to detect aliases
if [ -x /usr/bin/which ]; then
    alias which="alias | which --read-alias"
fi

# Listing directories
alias l.='ls -ld .*'
alias ll='ls -l'
alias la='ls -lA'
alias lh='ls -Aoh'
alias lt='command ls --color=auto -lAtr'

# Moving around
up() {
    if [ $# -eq 0 ]; then
        cd ..
    elif [ $# -eq 1 ]; then
        for ((i=0; i<$1; i++)); do
            cd ..
        done
    fi
}

# Connecting to places
alias fly='ssh -X kds124@flyweight.cs.rutgers.edu'
alias eden='ssh kds124@eden.rutgers.edu'

# Start Chromium
if [ -x /usr/bin/google-chrome ]; then
    alias chrome='google-chrome > /dev/null 2>&1 &'
    alias incognito='google-chrome --incognito > /dev/null 2>&1 &'
elif [ -x /usr/bin/chromium ]; then
    alias chrome='chromium > /dev/null 2>&1 &'
    alias incognito='chromium --incognito > /dev/null 2>&1 &'
fi

# Handy opener for files
if [ -x /usr/bin/xdg-open ]; then
    alias open='xdg-open'
elif [ -x /usr/bin/gvfs-open ]; then
    alias open='gvfs-open'
fi

# Set the desktop background
if [ -x /usr/bin/feh ] && [ -d ~/Pictures ]; then
    alias setbg='feh --bg-fill --no-fehbg'
    alias randombg='setbg ~/Pictures/$(ls ~/Pictures | sort -R | tail -n1)'
fi

# Compile LaTeX files non-interactively
if [ -x /usr/bin/pdflatex ]; then
    alias pdflatex='pdflatex -interaction nonstopmode -file-line-error'
fi

#" vim: filetype=sh
