# bashrc: executed by bash for non-login shells

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# History settings
export HISTCONTROL=ignoreboth
export HISTFILESIZE=20000
export HISTSIZE=10000

# Terminal settings
if which urxvt > /dev/null 2>&1 ; then
    export TERM='rxvt-unicode-256color'
else
    export TERM='xterm-256color'
fi

# Autocompletion
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# More autocompletion (may conflict with /etc/bash_completion)
complete -cf man
complete -cf sudo

# Other shell options
shopt -s autocd
shopt -s cdspell
shopt -s checkwinsize
shopt -s cmdhist
shopt -s dotglob
shopt -s expand_aliases
shopt -s extglob
shopt -s histappend
shopt -s hostcomplete
shopt -s nocaseglob

# Alias definitions
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Custom prompt
if [ -f ~/.bash_prompt ]; then
    . ~/.bash_prompt
else
    export PS1='\n[ \u@\h in \w ]\n\$ '
fi
